AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar journaling's project ID.

Resources:
  CWLtoKinesisFirehoseRole:
    Description: Creating service role in IAM for CloudWatch Logs
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectId}-CWLtoKinesisFirehoseRole'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [logs.ap-northeast-1.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: !Sub '${ProjectId}-Permissions-Policy-For-CWL'
        PolicyDocument:
          Statement:
          - Effect: "Allow"
            Action: ["firehose:*"]
            Resource: ["arn:aws:firehose:*"]
          - Effect: "Allow"
            Action: ["iam:PassRole"]
            Resource: ["arn:aws:iam::*"]
  SubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !Sub '/aws/lambda/awscodestar-${ProjectId}-lambd-CustomDefaultFunction-EK2SA1MNKIGU'
      FilterPattern: ''
      DestinationArn: !Sub 'arn:aws:firehose:ap-northeast-1:${AWS::AccountId}:deliverystream/${ProjectId}-log'
      RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ProjectId}-CWLtoKinesisFirehoseRole'